version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: auth_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV_MODE=prod

volumes:
  postgres_data: